groups:
- name: alert_rules
  rules:
  # Alert for CPU Usage for low env
  - alert: HighCPUUsage
    expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 85
    for: 2m
    labels:
      severity: warning
      environment: lower  
    annotations:
      summary: "High CPU usage detected on instance {{ $labels.instance }}"
      description: "CPU usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"

  # Alert for CPU Usage for prod env
  - alert: HighCPUUsage
    expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 85
    for: 2m
    labels:
      severity: warning
      environment: production
    annotations:
      summary: "High CPU usage detected on instance {{ $labels.instance }}"
      description: "CPU usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"
        
  # Alert for Memory Usage for low env
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 50
    for: 2m
    labels:
      severity: warning
      environment: lower   
    annotations:
      summary: "High Memory usage detected on instance {{ $labels.instance }}"
      description: "Memory usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"

  # Alert for Memory Usage for prod env
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 2m
    labels:
      severity: warning
      environment: production   
    annotations:
      summary: "High Memory usage detected on instance {{ $labels.instance }}"
      description: "Memory usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"
        
  # Alert for Disk Usage for low env
  - alert: HighDiskUsage
    expr: (node_filesystem_size_bytes{fstype!="tmpfs",mountpoint!="/run"} - node_filesystem_avail_bytes{fstype!="tmpfs",mountpoint!="/run"}) / node_filesystem_size_bytes{fstype!="tmpfs",mountpoint!="/run"} * 100 > 85
    for: 2m
    labels:
      severity: warning
      environment: lower 
    annotations:
      summary: "High Disk usage detected on instance {{ $labels.instance }}"
      description: "Disk usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"

  # Alert for Disk Usage for production
  - alert: HighDiskUsage
    expr: (node_filesystem_size_bytes{fstype!="tmpfs",mountpoint!="/run"} - node_filesystem_avail_bytes{fstype!="tmpfs",mountpoint!="/run"}) / node_filesystem_size_bytes{fstype!="tmpfs",mountpoint!="/run"} * 100 > 85
    for: 2m
    labels:
      severity: warning
      environment: production
    annotations:
      summary: "High Disk usage detected on instance {{ $labels.instance }}"
      description: "Disk usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"
        
  # Alert for Stopped Containers for low env
  - alert: StoppedContainers
    expr: engine_daemon_container_states_containers{state="exited"} > 0
    for: 2m
    labels:
      severity: critical
      environment: lower
    annotations:
      summary: "Container is down on instance {{ $labels.instance }}"
      description: "One or more containers have been in the exited state for more than 2 minutes."

  # Alert for Stopped Containers for prod env
  - alert: StoppedContainers
    expr: engine_daemon_container_states_containers{state="exited"} > 0
    for: 2m
    labels:
      severity: critical
      environment: production
    annotations:
      summary: "Container is down on instance {{ $labels.instance }}"
      description: "One or more containers have been in the exited state for more than 2 minutes."
        
