groups:
- name: alert_rules
  rules:
  # Alert for CPU Usage 
  - alert: HighCPUUsage
    expr: (100 - (avg by (instance, environment, alert_channel) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected on instance {{ $labels.instance }}. Current usage: {{ $value }}%"
      description: "CPU usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"

      # Alert for Memory Usage 
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High Memory usage detected on instance {{ $labels.instance }}. Current usage: {{ $value }}%"
      description: "Memory usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"

        
  # Alert for Disk Usage 
  # ⚠️ Warning (75–85 only)
  - alert: DiskUsageWarning
    expr: |
      (
        max(100 - ((node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"} * 100)
        / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"})) by (instance, environment, alert_channel) > 75
      )
      and
      (
        max(100 - ((node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"} * 100)
        / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"})) by (instance, environment, alert_channel) < 85
      )
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Disk usage above 75% on {{ $labels.instance }} (Current: {{ $value }}%)"
# 🚨 Critical (>85)
  - alert: DiskUsageCritical
    expr: |
      max(
        100 - ((node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"} * 100)
        / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"})
      ) by (instance, environment, alert_channel) > 85
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Disk usage above 85% on {{ $labels.instance }} (Current: {{ $value }}%)"        
  - alert: ContainerDown
    expr: engine_daemon_container_states_containers{state="running"} < 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Container Down on {{ $labels.instance }}"
      description: "Container {{ $labels.name }} is down on instance {{ $labels.instance }}."

  - alert: NoDataAlert
    expr: up{job="prod-apps-private-ip"} == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "No data in {{ $labels.instance }}"
      description: "No data in instance ({{ $labels.instance }})"

  - alert: NoDataAlert
    expr: up{job="low-env-public-ip"} == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "No data in {{ $labels.instance }}"
      description: "No data in instance ({{ $labels.instance }})"
       
  - alert: NoDataAlert
    expr: up{job="insure-public-ip"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "No data in {{ $labels.instance }}"
      description: "No data in instance ({{ $labels.instance }})"
      
        #- name: ssl-alerts
        #rules:
    #- alert: SSLCertificateExpiringSoon
    # expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 15
      #expr: vector(1)
      # for: 2m
      # labels:
      #severity: warning
        #environment: "{{ $labels.environment }}"
        #annotations:
      # summary: "SSL certificate for {{ $labels.instance }} is expiring soon — Expiry (IST): {{ ($value + 19800) | humanizeTimestamp }}"
        # description: |
        #SSL certificate for {{ $labels.instance }} will expire in less than 15 days.
        # Current expiry timestamp: {{ $value | humanizeTimestamp }}        
