apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: https://dc-prometheus.wrtual.in
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      httpMethod: GET
    secureJsonData:
      tlsSkipVerify: true  # This disables TLS verification

