{
 "title": "MAIN-DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"ec2-instances\"}, instance)"
    }
   },
   {
    "name": "container_name",
    "label": "container_name",
    "query": {
     "query": "label_values(engine_daemon_container_states_containers, container_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ALERTING-PANNEL", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PROD APPS CPU USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"prod-apps-private-ip\", mode=\"idle\"}[5m])) by (instance) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PROD APPS MEMORY USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job='prod-apps-private-ip'} - node_memory_MemFree_bytes{job='prod-apps-private-ip'} - node_memory_Buffers_bytes{job='prod-apps-private-ip'} - node_memory_Cached_bytes{job='prod-apps-private-ip'}) / node_memory_MemTotal_bytes{job='prod-apps-private-ip'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "PROD APPS DISK USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes{fstype!=\"tmpfs\", job=\"prod-apps-private-ip\"} * 100) / node_filesystem_size_bytes{fstype!=\"tmpfs\", job=\"prod-apps-private-ip\"})) \nby (instance, job, environment)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PROD DOCKER CONTAINER ALERT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job='prod-env-public-ip', state='running'}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "engine_daemon_container_states_containers{job='prod-env-private-ip', state='running'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LOW ENV APPS CPU USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"low-env-public-ip\", mode=\"idle\"}[5m])) by (instance) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"low-env-private-ip\", mode=\"idle\"}[5m])) by (instance) * 100)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"uat-env-public-ip\", mode=\"idle\"}[5m])) by (instance) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"uat-env-private-ip\", mode=\"idle\"}[5m])) by (instance) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LOW ENV APPS MEMORY USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job='low-env-public-ip'} - node_memory_MemFree_bytes{job='low-env-public-ip'} - node_memory_Buffers_bytes{job='low-env-public-ip'} - node_memory_Cached_bytes{job='low-env-public-ip'}) / node_memory_MemTotal_bytes{job='low-env-public-ip'}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job='uat-env-public-ip'} - node_memory_MemFree_bytes{job='uat-env-public-ip'} - node_memory_Buffers_bytes{job='uat-env-public-ip'} - node_memory_Cached_bytes{job='uat-env-public-ip'}) / node_memory_MemTotal_bytes{job='uat-env-public-ip'}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job='uat-env-private-ip'} \n- node_memory_MemFree_bytes{job='uat-env-private-ip'} \n- node_memory_Buffers_bytes{job='uat-env-private-ip'} \n- node_memory_Cached_bytes{job='uat-env-private-ip'}) \n/ node_memory_MemTotal_bytes{job='uat-env-private-ip'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LOW ENV APPS DISK USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes{fstype!=\"tmpfs\", job=\"low-env-private-ip\"} * 100) / node_filesystem_size_bytes{fstype!=\"tmpfs\", job=\"low-env-private-ip\"})) \nby (instance, job, environment)\n",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes{fstype!=\"tmpfs\", job=\"low-env-public-ip\"} * 100) / node_filesystem_size_bytes{fstype!=\"tmpfs\", job=\"low-env-public-ip\"})) \nby (instance, job, environment)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes{fstype!=\"tmpfs\", job=\"uat-env-private-ip\"} * 100) \n/ node_filesystem_size_bytes{fstype!=\"tmpfs\", job=\"uat-env-private-ip\"})) \nby (instance, job, environment)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes{fstype!=\"tmpfs\", job=\"uat-env-public-ip\"} * 100) \n/ node_filesystem_size_bytes{fstype!=\"tmpfs\", job=\"uat-env-public-ip\"})) \nby (instance, job, environment)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LOW ENV DOCKER CONTAINER ALERT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"lower-env-public-ip\",instance=\"UAT-1\",state=\"running\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "engine_daemon_container_states_containers{job=\"lower-env-public-ip\",instance=\"UAT-2(WAHOO+ELASTIC+XTREEMIS+EMM_PYTHON, demoappv2,am-dash, license-gateway,am-bridge,redis-insight,workflow,tvs,)+SFTP\",state=\"running\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "engine_daemon_container_states_containers{job=\"lower-env-public-ip\", instance=\"UAT_3_FIREBASEMS\",state=\"running\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "engine_daemon_container_states_containers{job=\"lower-env-public-ip\",instance=\"UAT-INTEL(datateam-airflow,redis-insight,leek,stage-kafkaui +uat-kafkaui))\",state=\"running\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "INSURE APPS CPU USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"insure-public-ip\", mode=\"idle\"}[5m])) by (instance) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INSURE APPS MEMORY USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job='insure-public-ip'} - node_memory_MemFree_bytes{job='insure-public-ip'} - node_memory_Buffers_bytes{job='insure-public-ip'} - node_memory_Cached_bytes{job='insure-public-ip'}) / node_memory_MemTotal_bytes{job='insure-public-ip'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "INSURE APPS DISK USAGE ALERT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes{fstype!=\"tmpfs\", job=\"insure-public-ip\"} * 100) / node_filesystem_size_bytes{fstype!=\"tmpfs\", job=\"insure-public-ip\"})) \nby (instance, job, environment)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}